### ISSUE TITLE
Haxe port

### ISSUE THREAD

**Issue by markknol** [VerbalExpressions/JSVerbalExpressions#105]
I ported the library to Haxe

https://github.com/markknol/hx-verbal-expressions

Can you add it to the list?

**Comment by jehna** [comment]
@markknol if it's ok for you, we can make a github.com/verbalexpressions/HaxeVerbalExpressions repo and add the admin rights to you? That will automatically add the project to http://verbalexpressions.github.io/

**Comment by markknol** [comment]
Can I also move / transport the current repository to this group or something? I am not that familiar with github.

**Comment by ionutvmi** [comment]
@markknol you should be all set up.
https://github.com/VerbalExpressions/HaxeVerbalExpressions
You can now push your code there.
Please confirm that is working ok and please let me know if you need more permissions for your repo.

**Comment by thesunlover** [comment]
+1 super

**Comment by markknol** [comment]
@ionutvmi Is it also okay that I transfer the current repository to the organisation? I need temporary admin rights for that. I can rename to HaxeVerbalExpressions afterwards.

![image](https://cloud.githubusercontent.com/assets/576184/12167404/4773fbe4-b52c-11e5-9825-ce8232209bed.png)

**Comment by ionutvmi** [comment]
It's ok with me.  
Is there any specific reason why you want to transfer the repo or just for the redirect ?

**Comment by markknol** [comment]
To keep the stars and the redirect. I now transferred the repos.

I think this repository can be now be removed safely, right? 
https://github.com/VerbalExpressions/HaxeVerbalExpressions < can be removed

**Comment by ionutvmi** [comment]
It was removed. 
Please rename your repo to HaxeVerbalExpressions.

**Comment by markknol** [comment]
done!
