### ISSUE TITLE
explain()/interpret() function?

### ISSUE THREAD

**Issue by ajakubo1** [VerbalExpressions/JSVerbalExpressions#111]
Hi!

I have a question about the library - does it have a function which allows you to check what kind of regex will be built? I think it's gonna be useful for educational purposes ;).

Best Regards and thanks for the work you've done!

**Comment by softwarespot** [comment]
What about using toRegExp() and then using toString() on the object?

**Comment by ajakubo1** [comment]
Ha! Sorry, I've just found out that calling console.log() on created regex outputs the string :). works for me.
