### ISSUE TITLE
PureScript port

### ISSUE THREAD

**Issue by sharkdp** [VerbalExpressions/JSVerbalExpressions#121]
In case anyone is interested, here is an implementation in PureScript, using free monads:
https://github.com/sharkdp/purescript-verbal-expressions

**Comment by ionutvmi** [comment]
https://github.com/VerbalExpressions/PurescriptVerbalExpressions
You should be all set up.

Please let me know if you need more permissions there.

**Comment by sharkdp** [comment]
Thank you!

I know it's unfortunate because it doesn't fit the naming of the other VerbalExpression repositories, but it would be great if you could rename the repository to
```
purescript-verbal-expressions
```
(similar to the `elm-` version), because this is the standard naming convention for PureScript modules

**Comment by ionutvmi** [comment]
The repo was renamed.

**Comment by sharkdp** [comment]
Thanks alot!
