### ISSUE TITLE
Add to CDN

### ISSUE THREAD

**Issue by jehna** [VerbalExpressions/JSVerbalExpressions#124]
Related to #123

**Comment by tomByrer** [comment]
I can do that for you (I happen to volunteer for [jsDelivr OSS CDN](http://www.jsdelivr.com/).  I'm fairly certain that our [@120 POPs](http://www.jsdelivr.com/features/network-map) should be sufficient ;)

But I prefer to host only minified files, so I hope you upload those.  Many [tools](https://www.npmjs.com/search?q=minify) are available to help, even [online](http://refresh-sf.com/).  Good news is if you tag [releases](https://github.com/VerbalExpressions/JSVerbalExpressions/releases), then it easy to [configure our bot](https://github.com/jsdelivr/jsdelivr/blob/master/CONTRIBUTING.md) to automate all update uploads for you.

**Comment by mackenza** [comment]
@tomByrer there is already a grunt job in the release to produce a minified library. Does the CDN also house map files usually?

**Comment by tomByrer** [comment]
That's great you have the script ready to compress, but the actual `
verbalexpressions.min.js
<https://github.com/VerbalExpressions/JSVerbalExpressions/blob/master/VerbalExpressions.js>
` output needs to be hosted in the GH repo.  Our bot is not strong enough
to run grunt or gulp tasks.  :/

BTW, I've seen issues with mixed case filenames; best practice to use only
lowercase.
https://github.com/ractivejs/ractive/issues/527#issue-30274600

Sure, we're happy to host `.map` files.

On Mon, Jan 11, 2016 at 10:55 AM, Andrew MacKenzie <notifications@github.com

**Comment by tomByrer** [comment]
(BTW, thanks for including a header comment in the `.min.js` & ending the IIFE with a `;`; both help prevent problems.)

**Comment by softwarespot** [comment]
Once done, I can then look at using a grunt umd wrapper instead, which I was looking at the other day, but made no sense if the user had to build the library themselves.

**Comment by ionutvmi** [comment]
@tomByrer a PR was created for this https://github.com/jsdelivr/jsdelivr/pull/8882
A new release was created: https://github.com/VerbalExpressions/JSVerbalExpressions/releases/tag/0.2.0

**Comment by ionutvmi** [comment]
:fireworks: :smile:  :fireworks: 
http://www.jsdelivr.com/projects/jsverbalexpressions
