### ISSUE TITLE
Getting VerEx is not a function!

### ISSUE THREAD

**Issue by bhaveshgohel** [VerbalExpressions/JSVerbalExpressions#132]
Can anyone help me to spot the mistake - https://tonicdev.com/bhaveshgohel/56a1d52f73c7940d00fa20db ?

**Comment by ionutvmi** [comment]
This was actually a bug in 0.2.0, it should be fixed in 0.2.1
Please confirm.

**Comment by bhaveshgohel** [comment]
Fixed in 0.2.1!  Thanks. :+1:

**Comment by softwarespot** [comment]
A little confused as to why this happened, since this should be window normally and module is defined on window

**Comment by ionutvmi** [comment]
In nodejs `this` in the global scope refers to the current module not the `global` object.

**Comment by softwarespot** [comment]
My bad, I didn't take this fact into account. Sorry.
