### ISSUE TITLE
Moving to gulp

### ISSUE THREAD

**Issue by softwarespot** [VerbalExpressions/JSVerbalExpressions#135]
I first started out using Grunt, but over time have migrated to gulp. I don't really want to do a whole [comparison](https://medium.com/@preslavrachev/gulp-vs-grunt-why-one-why-the-other-f5d3b398edc4#.ttd71d7df) of why gulp is better than Grunt, just that if people are happy to use gulp, I can create a PR that migrates the build tasks to gulp.

**Comment by jehna** [comment]
At least I'm comfortable with Grunt. But yeah, I think Grunt vs Gulp is like Pepsi vs Coke.

**Comment by softwarespot** [comment]
Okay, we can leave it as it is then. There are some added benefits to using gulp though, one of which is speed and use of streams

**Comment by jehna** [comment]
But with Grunt you can use `grunt-concurrent` to make things even faster than Gulp's pipes. So in the end, it's all about preference :)
