### ISSUE TITLE
Make a captured group optional

### ISSUE THREAD

**Issue by RomainGoncalves** [VerbalExpressions/JSVerbalExpressions#139]
Hey,

I was just wondering how I can get a captured group optional? Basically just adding '?' at the end of the group.

I have this so far:
```
javascript
var regex = VerEx()
      .startOfLine()
      .then(code)
      .then('_')
      .range('0', 9)
      .oneOrMore()
      .then(letter)
      .beginCapture()
      .then('_')
      .range('0', 9)
      .oneOrMore()
      .endCapture();
```

Which gives me this: ```
^(?:COO)(?:_)[0-9]+(?:A)((?:_)[0-9]+)/gm```

Good, but I'd like: ```
^(?:COO)(?:_)[0-9]+(?:A)((?:_)[0-9]+)?/gm```

I'm trying to match:
COO_001A
COO_001A_1
COO_001A_9
COO_001A_11
COO_022222201A_1122222

And so far, they all match but not: COO_001A

**Comment by ionutvmi** [comment]
Since we don't have a method for it you can always use the `add` method to append a custom part.
```
VerEx()
      .startOfLine()
      .then('COO')
      .then('_')
      .range(0, 9)
      .oneOrMore()
      .then('A')
      .beginCapture()
      .then('_')
      .range(0, 9)
      .oneOrMore()
      .endCapture()
      .add('?');
```

**Comment by RomainGoncalves** [comment]
Ah great! Thanks
