### ISSUE TITLE
Maybe not working N times

### ISSUE THREAD

**Issue by kuashe** [VerbalExpressions/JSVerbalExpressions#142]
Implementation repo is saying that the maybe statement should work for 0 - N Times

[https://github.com/VerbalExpressions/implementation/wiki/List-of-methods-to-implement#maybe](url)

Actually it only work one time. 

```
   var regex = VerEx().find("a").maybe(" ").find("b")
    
    var code = "a  b" // Two spaces between a and b
    
    console.log(regex.test(code)) //false
```

Is this normal that api is different from implementation ?

**Comment by jehna** [comment]
The language versions still have some differences and the `/implementation` repository has discussion about future work of unifying the contents.

For javascript, you can find the most up-to-date documentation from [docs/ folder](https://github.com/VerbalExpressions/JSVerbalExpressions/tree/master/dist/docs/verbal-expressions/0.2.1).

You probably want to use `multiple()` to achieve your goal:
```
var regex = VerEx().find("a").multiple(" ").find("b");
var code = "a  b";
console.log(regex.test(code)); // true
```

**Comment by kuashe** [comment]
That's what is was looking for i guess , this can be marked as closed .

Thanks a lot for this !
