### ISSUE TITLE
Vala port

### ISSUE THREAD

**Issue by desiderantes** [VerbalExpressions/JSVerbalExpressions#145]
I'm finishing a [Vala](http://vala-project.org) port of this lib, and i'd like to publish it alongside the other implementations.

**Comment by ionutvmi** [comment]
There you go https://github.com/VerbalExpressions/ValaVerbalExpressions 
Please confirm that you have push access and close this issue.
Please let me know if you need admin access to that repo.

**Comment by desiderantes** [comment]
Sorry, i don't have push access to that repo

**Comment by desiderantes** [comment]
It works now, thanks
