### ISSUE TITLE
how do I write this expression

### ISSUE THREAD

**Issue by komoe** [VerbalExpressions/JSVerbalExpressions#147]
//          192.168._._
//          192.168.168.1-96
//          192.168.1-96.*
//          google.com
Excuse me,No one has time to help me write a match on the above expression

**Comment by jehna** [comment]
@komoe Which of these are you trying to match?
1. any ip + ip range + domain
2. any ip or ip range starting "192.168" or any domain
3. literally those four lines

**Comment by omkarkothavale88** [comment]
whats the exact question?

**Comment by shreyasminocha** [comment]
@jehna, this should be closed. The author isn't interested in getting their question answered. Also, I don't think 'issues' is the right place for such queries.

**Comment by codingjavascripttoday** [comment]
Let's try this. This will match line two and help you understand the pattern. I agree with above not enough info. But consider the below example, considering the numbers are always the same format, would be something like this.

let findMatch = new RegExp(/[0-9]{3}\.[0-9]{3}/);

**Comment by jehna** [comment]
Closing this issue because of the OPs inactivity
