### ISSUE TITLE
Typescript definition

### ISSUE THREAD

**Issue by marviobezerra** [VerbalExpressions/JSVerbalExpressions#150]
Is there a typescript definition? I searched for it on definitelytyped without luck.

**Comment by jehna** [comment]
there's not one available at the time

**Comment by ionutvmi** [comment]
@marviobezerra I added a first draft here https://github.com/VerbalExpressions/JSVerbalExpressions/blob/master/typings/VerbalExpression.d.ts

Feel free to contribute if you are more familiar to them.
