### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by ceres629** [VerbalExpressions/JSVerbalExpressions#158]
Am I overlooking something but there doesn't seem to be any documentation on how to use this. It seems really useful, but there aren't any meaningful examples of how to use it and the documentation doesn't even list all available functions. Even though VerbalExpressions are much easier in theory I end up just going back to regex, simply because there is documentation on how to use regex, but none on how to use this, which is unfortunate because just a handle full of common basic examples would suffice.

**Comment by jehna** [comment]
Please see the [wiki](https://github.com/VerbalExpressions/JSVerbalExpressions/wiki) section of the page, it has some documentation.

The documentation is still work in progress, so feel free to contribute 😃 

The documentation link should probably be added to the readme.

**Comment by shreyasminocha** [comment]
#168 replaces the wiki docs and adds a [more-or-less complete set of documentation](https://verbalexpressions.github.io/JSVerbalExpressions). Feel free to contribute to it.
