### ISSUE TITLE
Bug in sanitize function

### ISSUE THREAD

**Issue by waitingcheung** [VerbalExpressions/JSVerbalExpressions#160]
The [``sanitize``](https://github.com/VerbalExpressions/JSVerbalExpressions/blob/master/VerbalExpressions.js#L68) function misses some values that may cause a TypeError.

For example, if ``value`` does not have the property ``source``, ``value.source`` causes a TypeError.

If ``value`` is not a string, calling ``value.replace`` causes a TypeError.

Here is a suggested fix:
```js
// Change the check to following
if (value && value.source)

// Add this before the line reRegExpEscape = ... to return a default string
if (typeof value !== 'string') {
    return '';
}
```

**Comment by shreyasminocha** [comment]
I think this is no longer valid.

**Comment by codexnovus** [comment]
Can confirm it. This simple script will generate the error

const verex = require('verbal-expressions');
const expression = verex().startOfLine().then(':: ').beginCapture().digit().oneOrMore().endCapture().then(' ').anything().multiple().endOfLine();
console.log(expression.toRegExp());
