### ISSUE TITLE
Bug in `multiple`

### ISSUE THREAD

**Issue by shreyasminocha** [VerbalExpressions/JSVerbalExpressions#171]
As pointed out by @codexnovus, 

```
const verex = require('verbal-expressions');
const expression = verex().startOfLine().then(':: ').beginCapture().digit().oneOrMore().endCapture().then(' ').anything().multiple().endOfLine();
console.log(expression.toRegExp());
```

gives an error. Removing the call to `multiple` fixes the error.

This is not a bug with `sanitize` as @codexnovus suspected but a bug with `multiple` caused by a faulty call to `sanitize`.

**Comment by ionutvmi** [comment]
There was also a discussion about the implementation of multiple here: https://github.com/VerbalExpressions/implementation/issues/2
