### ISSUE TITLE
Update on npm

### ISSUE THREAD

**Issue by shreyasminocha** [VerbalExpressions/JSVerbalExpressions#185]
The npm package is still on 0.3.0. Notable changes since include several bugs fixes, backward-incompatible changes to `multiple`'s API (among others IIRC), and the addition of `not` and `sanitize`. Personally, I feel we're ready for 1.0.0 especially since we now have a complete set of tests and docs.

**Comment by ionutvmi** [comment]
https://www.npmjs.com/package/verbal-expressions

#1.0.0 has been published.

Please review and let me know if you have any concerns.

**Comment by shreyasminocha** [comment]
Lgtm

**Comment by shreyasminocha** [comment]
@ionutvmi Please tag the release via git as well? At the moment CDNs still have `0.3.0`.

**Comment by ionutvmi** [comment]
@shreyasminocha  the tag and the release has been created: https://github.com/VerbalExpressions/JSVerbalExpressions/releases

**Comment by shreyasminocha** [comment]
Thanks.
