### ISSUE TITLE
Docs examples for `multiple`

### ISSUE THREAD

**Issue by gjmcn** [VerbalExpressions/JSVerbalExpressions#199]
Hi,

The examples in the docs for `multiple` with `min` (or `min` and `max`) are not working as expected. Rather than e.g.

```js
const expr = VerEx()
    .find('hurray').then('!').multiple(1)
    .endOfLine();
```

I think it should be:

```js
const expr = VerEx()
    .find('hurray').multiple('!', 1)
    .endOfLine();
```

Is it this simple or am I missing something about how `multiple` can be applied to the preceding thing?

Thanks.

**Comment by shreyasminocha** [comment]
You're right. Would it be possible for you to create a PR that fixes the docs?
