### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by jehna** [VerbalExpressions/JSVerbalExpressions#2]
Add clear API documentation

**Comment by shreyasminocha** [comment]
I think we should have documentation in the README itself. That's the first place I'd look for documentation. What do you guys think?

**Comment by shreyasminocha** [comment]
Right now, we have documentation in two places: the wiki and the jsdoc generated docs in `dist/docs/`. For maintainability's sake, it should be either one or the other. Alternatively, we could have manually written docs either in separate markdown files or within README. The advantages to this approach are:

- They would be under version control along with the library
- Easier to control quality vs using the wiki
- No doc comments in the code.

If we choose to keep just the jsdoc generated documentation, we should probably generate a `.github.io` webpage  from the `dist/docs/` folder to make them more accessible.

**Comment by shreyasminocha** [comment]
Vote to close. #168.
