### ISSUE TITLE
State of JSVerbalexpressions

### ISSUE THREAD

**Issue by jehna** [VerbalExpressions/JSVerbalExpressions#205]
Hey @shreyasminocha and @ionutvmi

First of all I want to thank you for your work towards this project during the years. I know maintaining an open-source library can be an ungrateful job, and I want you to have the credit that belongs to you.

There hasn't been that much communication between the maintainers, and I get that everyone has things that are much more important than this (at least I do). I would like to do a small cleanup for this project as it is now, like update dependencies, do a little maintenance on the infrastructure etc. to make this project easier to maintain for myself.

Is this project still something that you two feel you want to have ownership in? If so, I'm happy to bounce my code through pull requests and have you get saying on things. But if you don't have the time and you'd be okay if I do some janitor work by myself, then I'm happy to take bigger ownership of this project than before (for the time being) and not bother you with my pull requests.

Let me know what you think!

**Comment by shreyasminocha** [comment]
Hey @jehna—glad to see some activity on here :D. I'm a bit busier than usual, but this is still something that's important to me. Give me a shout if there are API changes or if there's something you'd prefer input on, but at the same time if it's mostly meta stuff like you say, I trust your judgement :)

**Comment by DevAngsy** [comment]
@jehna Thanks very much!
