### ISSUE TITLE
Usage example?

### ISSUE THREAD

**Issue by gsklee** [VerbalExpressions/JSVerbalExpressions#77]
This looks like a brilliant idea at first but then I've encountered some difficulties immediately trying to convert a very basic Regex to Verex:

``` javascript
string.split(/\s(.+)?/, 2)
```

How do I rewrite this in Verex?

Also, an online sandbox that display Verex and the equivalent Regex side-by-side would be really helpful.

**Comment by mackenza** [comment]
with all regex questions it's useful to provide a string or strings of what you expect to match to help diagnose.

Is the `string.split()` you have above actually working? What I see is:
* somewhere on the line (doesn't have to be first), match a single whitespace character
* then capture anything except newline
The `?` after the capture group confuses me. I don't know how to explain or represent it in VerEx.

Based on that, in VerEx you would do:
```
var tester = VerEx()
    .whitespace()
    .beginCapture()
    .something()
    .endCapture()
    .stopAtFirst()
    .searchOneLine();
```
but again, I am not sure what you expect to match so I cannot say for sure it's a desired outcome. `tester = /\s((?:.+))/ ` based on what I gave you above which is functionally what your example shows.

**Comment by lf-araujo** [comment]
Very sorry to piggyback on this question, but I am failing to reproduce the following regular expression using VerEx:

`(?s)(?<=---).*(?=---) `


I wanted to extract any text between two sets of '---' in a string, is it possible?

Thank you.

**Comment by shreyasminocha** [comment]
@lf-araujo Sorry for the late response, but VerbalExpressions doesn't have support for lookaheads and [lookbehinds](https://github.com/tc39/proposal-regexp-lookbehind) at the moment. You could probably try to write a verbal expression equivalent to `/---(.*)---/g` and retrieve the capture group.

Original question seems to have been answered some years back. Online sandbox now exists at https://verbalregex.com thanks to @BachNX & @KhanhTC.
