### ISSUE TITLE
Documentation - JSFiddle Link

### ISSUE THREAD

**Issue by TheJaredWilcurt** [VerbalExpressions/JSVerbalExpressions#82]
Could you supply a link in the ReadMe.md to jsFiddle with an already set up project to test/play around with.

Something like this:
* ~~http://jsfiddle.net/nmz8o8b6/~~

* * *

**Edit:** Updated to version 0.3.0 (2018)
* http://jsfiddle.net/nmz8o8b6/8/

**Comment by jehna** [comment]
Better yet, one could make an interactive js widget to the [VerbalExpressions GitHub site](http://verbalexpressions.github.io/).

I'm thinking something like: http://www.typescriptlang.org/Playground

**Comment by mackenza** [comment]
@jehna you don't really need to do your own playground. Just embed one of the playgrounds in your site. I prefer JSBin to JSFiddle because it gives access to the console.

Once this library is on a CDN, it will be easy to do this where you set up the basics of using JSVerbalExpressions and then embed it in the website to allow people to play.

I can do it and submit a PR if you want?

**Comment by TheJaredWilcurt** [comment]
@mackenza 

Either is fine, I just think it's a lot easier to understand jsfiddle's:

    console.log( tester );

than it is to understand jsbin's

    console.log( "/" + tester._prefixes + tester._source + tester._suffixes + "/" + tester._modifiers );

JSFiddle, gives you the same access to the console that any website does. JSBin does a poor attempt at trying to display that information on the page. Either way, we should be having a live demo, I just think JSFiddle is less confusing.

* http://jsfiddle.net/nmz8o8b6/2/
* https://jsbin.com/xowilokoro/edit?js,console

**Comment by mackenza** [comment]
@TheJaredWilcurt  - fair enough. I agree, just using the regular browser console is a better way of handling this ;)

I added the raw URL to the minified resource here on GitHub and though it complained (as GH is not a CDN) it still worked. So when we get a proper CDN URI we should update the JSFiddle to reflect that and not have the script in the HTML.

I am wondering if we really want an HTML playground at all. A Node REPL would be better at showing the use of the library, I think. How it fits in to a web page is entirely a different thing. What we are trying to do is to get the VerEx method chaining correct. Agreed?

I will look for such a thing.

**Comment by mackenza** [comment]
I have found and experimented with: https://github.com/Idered/Editr.js
This is easily embedded into the static org site and is able to hide the HTML and CSS tabs so you can focus on the JS and result.
I will try to have this in a PR for the org repo tomorrow if I get time.

**Comment by TheJaredWilcurt** [comment]
@mackenza All I use VerbalExpressions for is easily generating the regex string for me, then I just use that in my code to forgo the library in my repo. **100%** of my use of VerbalExpressions is on that JSFiddle link. Without that I would not ever touch this library.

**Comment by mackenza** [comment]
fair enough. I would think you would want to update the JSFiddle link with the CDN URL for JSDelivr to clean it up a bit, though.

As for the #127 I see your point that this is a separate thing and not mutually exclusive to having a JSFiddle link AND a playground.

**Comment by TheJaredWilcurt** [comment]
What's the CDN URL

**Comment by mackenza** [comment]
#124

**Comment by TheJaredWilcurt** [comment]
* https://cdn.jsdelivr.net/jsverbalexpressions/0.2.0/verbalexpressions.js

None of the links on that CDN work. I tried on my home internet and on my phone. Both return "File not found".

**Comment by mackenza** [comment]
I logged jsdelivr/jsdelivr#8941

**Comment by jehna** [comment]
Does jsdelivr support any syntax to fetch the latest release (like https://cdn.jsdelivr.net/jsverbalexpressions/latest/verbalexpressions.js)?

**Comment by trungtin** [comment]
@jehna Yes they do. And your syntax is correct, it's just that currently their CDN are down, nothing seem to works.

**Comment by jehna** [comment]
Thank you @trungtin.

@TheJaredWilcurt We should use the `/latest/` url in the JSFiddle

**Comment by mackenza** [comment]
when I logged the issue, other libraries worked fine, it was just this one broken. They have fixed jsdelivr/jsdelivr#8941 and the files work now.

**Comment by TheJaredWilcurt** [comment]
* http://jsfiddle.net/nmz8o8b6/4/
* https://jsbin.com/jaxivafezu/edit?js,console

**Comment by jehna** [comment]
@TheJaredWilcurt can you change the `0.2.0` part from the js library url to `latest`? This would guarantee that the fiddle and bin are using the latest libraries.

**Comment by TheJaredWilcurt** [comment]
* http://jsfiddle.net/nmz8o8b6/5/
* https://jsbin.com/jaxivafezu/edit?js,console

**Comment by shreyasminocha** [comment]
https://jsfiddle.net/shreyasminocha/gg8dqg6x/
