### ISSUE TITLE
Port to Rust

### ISSUE THREAD

**Issue by apopiak** [VerbalExpressions/JSVerbalExpressions#83]
I'm starting a port to Rust:
https://github.com/apopiak/RustVerbalExpressions

**Comment by ionutvmi** [comment]
You should be all set up https://github.com/VerbalExpressions/RustVerbalExpressions

**Comment by apopiak** [comment]
cool :+1:

**Comment by ionutvmi** [comment]
Closing this issue as it is complete.
Please let me know if you have any issues with the access.
