### ISSUE TITLE
Lua Port

### ISSUE THREAD

**Issue by Apprehentice** [VerbalExpressions/JSVerbalExpressions#86]
About a year ago, I ported Verbal Expressions to Lua. I just now found your addition instructions.
The port can be found at https://github.com/Apprehentice/vex

**Comment by ionutvmi** [comment]
You should be all set up: https://github.com/VerbalExpressions/LuaVerbalExpressions
Please let me know if you have access there and you can push.

**Comment by Apprehentice** [comment]
The content has been pushed.
