### ISSUE TITLE
Elm port

### ISSUE THREAD

**Issue by lukewestby** [VerbalExpressions/JSVerbalExpressions#87]
Hiya!

I created an Elm port here: https://github.com/lukewestby/ElmVerbalExpressions

It's virtually a direct port of this JS implementation with the exception that I renamed some of the functions if they were keywords (elm doesn't allow this) or very common core functions with established meaning, such as `andThen`, `maybe`, and `or`. I also left off the aliases that didn't have additional semantic meaning, such as `any`/`anyOf` and `lineBreak`/`br`. Any of these name changes are 100% up for discussion and feedback.

There's still some missing documentation a couple of missing tests and so it hasn't been published on the elm package registry yet, but I wanted to run it by you in the mean time to see what you think.

Thanks!

**Comment by ionutvmi** [comment]
https://github.com/VerbalExpressions/ElmVerbalExpressions

Can you add some code examples in the readme please.
Also some description about the limitiation of the function name and maybe a small table to show the differences between js and the elm api.

**Comment by lukewestby** [comment]
Thanks! I sure can. I'll add a basic example usage to demonstrate that the API is `|>`-operator-driven, and include the table of renames and reasons for the renaming. I don't think it will be necessary to include an entire set of API docs in the README as package.elm-lang.org generates very nice, browsable documentation automatically from the source and comments, but if you'd like to have that in the README as well I can certainly include it.

**Comment by lukewestby** [comment]
@ionutvmi I've made the updates in my repo. Also, I failed to remember that Elm package repos must be in dash-case if they are to be published, so would it be possible to rename to `elm-verbal-expressions` before moving the code over?

**Comment by ionutvmi** [comment]
I have renamed it https://github.com/VerbalExpressions/elm-verbal-expressions
The readme looks good. Please also include the `Other implementations` are similar to other repos: [exmple](https://github.com/VerbalExpressions/SwiftVerbalExpressions)

**Comment by lukewestby** [comment]
@ionutvmi thanks! so far so good, we're all set with the Other Implementations section. I think now I just need to be given write permissions to the repo so I can transfer the code.

**Comment by ionutvmi** [comment]
You should already have permissions to push.

**Comment by lukewestby** [comment]
I thought that would be the case as well, but I get a 403 response when I try to push to the repo, and I've attached a screenshot from the Contributors team in the organization showing that `elm-verbal-expressions` is set to read-only:

![screen shot 2016-01-04 at 7 04 41 am](https://cloud.githubusercontent.com/assets/1508245/12090140/a381d654-b2b1-11e5-83a8-19bca33ffc93.png)

**Comment by ionutvmi** [comment]
Yes, sorry about that.
I have updated the permissions it should be ok now.

**Comment by lukewestby** [comment]
Cool, no worries! Code is pushed and published http://package.elm-lang.org/packages/VerbalExpressions/elm-verbal-expressions/1.0.0/

Thanks for all your help!

**Comment by lukewestby** [comment]
@ionutvmi one more question, actually: are y'all open to adding creators of ports as owners of their respective repos? i'd love to be able to set the default branch and things like that if it's cool with you. thanks either way!

**Comment by lukewestby** [comment]
Awesome, thank you so much!
