### ISSUE TITLE
F# Port

### ISSUE THREAD

**Issue by jackfoxy** [VerbalExpressions/JSVerbalExpressions#88]
Nearly done with F# port, FsVerbalExpressions, should be ready to push next weekend. Thanks.

**Comment by ionutvmi** [comment]
The repository was created. Please confirm that you have permissions to push.
https://github.com/VerbalExpressions/FSharpVerbalExpressions

**Comment by jackfoxy** [comment]
Thanks, not sure how I go about doing that without actually pushing. I plan to push this weekend. I was just working on the project, mostly documenting and fine-tuning, but have to run off to the dentist now.

**Comment by jehna** [comment]
@jackfoxy you can test the pushing with `--dry-run` parameter. It doesn't actually push anything, but prompts you if there's any errors:
```
git push origin master --dry-run
```

**Comment by jackfoxy** [comment]
F# Port is pushed...still working on docs.

**Comment by jackfoxy** [comment]
Apparently I do not have access to the repository settings. Please add the GitHub Pages to FSharpVerbalExpressions http://verbalexpressions.github.io/FSharpVerbalExpressions/

thanks

**Comment by ionutvmi** [comment]
@jackfoxy you should have full access now.

**Comment by jackfoxy** [comment]
Thanks!
