### ISSUE TITLE
Dart port

### ISSUE THREAD

**Issue by Ne4istb** [VerbalExpressions/JSVerbalExpressions#97]
I'm working on Dart port, could you create a repo for this, please?

**Comment by ionutvmi** [comment]
https://github.com/VerbalExpressions/DartVerbalExpressions

Please let me know if you need more permissions for that repo.

**Comment by ionutvmi** [comment]
closing this as the access seems to work fine,

**Comment by Ne4istb** [comment]
@ionutvmi Thanks, access works fine, but, for some reasons, https://api.github.com/orgs/VerbalExpressions/repos (used in verbalExpressions.github.io) does not return this repo in the list. Could it be some specific option in repository or organization settings?

**Comment by ionutvmi** [comment]
@Ne4istb good catch.
It was caused by the github api pagination. By default is 30.
Should be fixed now.

**Comment by Ne4istb** [comment]
@ionutvmi Thanks
